version: 2
updates:
- package-ecosystem: gradle
  directory: "/compose-multiplatform"
  schedule:
    interval: daily
    time: "16:30"
    timezone: "Europe/Prague"
  cooldown:
    default-days: 7
    exclude:
    - "glass.yasan.*"
  labels: 
    - 'compose multiplatform'
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"
  groups:
    kotlin:
      patterns:
        - "jetbrains.kotlin.*"
    android-x:
      patterns:
        - "androidx.*"
    glass-yasan:
      patterns:
        - "glass.yasan.*"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "16:30"
    timezone: "Europe/Prague"
  cooldown:
    default-days: 7
  labels: 
    - 'github actions'
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"
