version: 2
updates:
- package-ecosystem: gradle
  directory: "/compose-multiplatform"
  schedule:
    interval: monthly
    timezone: "Europe/Prague"
  rebase-strategy: disabled
  labels:
    - 'compose multiplatform'
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"
  groups:
    kotlin:
      patterns:
        - "jetbrains.kotlin.*"
    android-x:
      patterns:
        - "androidx.*"
    glass-yasan:
      patterns:
        - "glass.yasan.*"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    timezone: "Europe/Prague"
  rebase-strategy: disabled
  labels:
    - 'github actions'
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"
